-- Free Ticket Events (rewarded video ads)
-- Run in Supabase SQL Editor

create table if not exists public.ad_ticket_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz default now(),
  event_type text not null check (event_type in ('wednesday', 'sunday')),
  week_id text not null
);

create index if not exists ad_ticket_events_user_id_idx on public.ad_ticket_events (user_id);
create index if not exists ad_ticket_events_week_event_idx on public.ad_ticket_events (week_id, event_type);
create index if not exists ad_ticket_events_created_idx on public.ad_ticket_events (created_at desc);

alter table public.ad_ticket_events enable row level security;

create policy "Users can read own ad_ticket_events"
  on public.ad_ticket_events for select
  using (auth.uid() = user_id);

create policy "Users can insert own ad_ticket_events"
  on public.ad_ticket_events for insert
  with check (auth.uid() = user_id);

-- Function to add ticket to user_stats when ad_ticket_events record is inserted
create or replace function public.on_ad_ticket_earned()
returns trigger
language plpgsql
security definer
as $$
begin
  insert into public.user_stats (user_id, tiket)
  values (new.user_id, 1)
  on conflict (user_id)
  do update set
    tiket = public.user_stats.tiket + 1,
    updated_at = now();

  insert into public.notifications (user_id, title, message)
  values (new.user_id, 'Ticket Earned!', 'You earned +1 ticket from watching an ad.');

  return new;
end;
$$;

drop trigger if exists ad_ticket_events_reward_trigger on public.ad_ticket_events;
create trigger ad_ticket_events_reward_trigger
  after insert on public.ad_ticket_events
  for each row execute function public.on_ad_ticket_earned();
