-- =============================================================================
-- TEK KAPSAMLI KURULUM - uuid/text uyumluluğu + Storage + Deals + Biletler
-- Supabase SQL Editor'a yapıştırıp çalıştırın. Tüm hataları düzeltir.
-- =============================================================================

-- ========== 0. MEVCUT uuid SÜTUNLARI TEXT'E ÇEVİR (uuid=text hatasını önler) ==========
do $$
begin
  if exists (select 1 from information_schema.columns where table_schema='public' and table_name='user_tickets' and column_name='user_id' and data_type='uuid') then
    alter table public.user_tickets alter column user_id type text using user_id::text;
    raise notice 'user_tickets.user_id uuid -> text';
  end if;
  if exists (select 1 from information_schema.columns where table_schema='public' and table_name='lottery_tickets' and column_name='user_id' and data_type='uuid') then
    alter table public.lottery_tickets alter column user_id type text using user_id::text;
    raise notice 'lottery_tickets.user_id uuid -> text';
  end if;
  if exists (select 1 from information_schema.columns where table_schema='public' and table_name='user_stats' and column_name='user_id' and data_type='uuid') then
    alter table public.user_stats alter column user_id type text using user_id::text;
    raise notice 'user_stats.user_id uuid -> text';
  end if;
end $$;

-- ========== 1. TABLOLAR (user_id TEXT tutarlı) ==========
create table if not exists public.user_stats (
  user_id text primary key,
  cuan integer not null default 0,
  tiket integer not null default 0,
  nickname text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.user_stats
  add column if not exists total_receipts integer not null default 0,
  add column if not exists level integer not null default 1,
  add column if not exists current_streak integer not null default 0,
  add column if not exists last_upload_date date;

create table if not exists public.user_tickets (
  user_id text not null,
  draw_week integer not null,
  tickets integer not null default 0,
  updated_at timestamptz default now(),
  primary key (user_id, draw_week)
);
create index if not exists user_tickets_draw_week_idx on public.user_tickets (draw_week);

create table if not exists public.lottery_tickets (
  id bigserial primary key,
  user_id text not null,
  draw_week integer not null,
  created_at timestamptz default now()
);
create index if not exists lottery_tickets_draw_week_idx on public.lottery_tickets (draw_week);

create table if not exists public.weekly_lottery (
  id bigserial primary key,
  draw_date date not null,
  winner_user_id text not null,
  tickets_used integer not null,
  reward_amount integer not null default 100000,
  created_at timestamptz not null default now()
);
create index if not exists weekly_lottery_draw_date_idx on public.weekly_lottery (draw_date);

create table if not exists public.weekly_winners (
  id bigserial primary key,
  user_id text,
  draw_date date,
  prize_amount integer default 100000,
  created_at timestamptz not null default now()
);
create index if not exists weekly_winners_created_at_idx on public.weekly_winners (created_at desc);

create table if not exists public.deals (
  id bigint generated by default as identity primary key,
  lat double precision not null,
  lng double precision not null,
  product_name text,
  price integer,
  store text,
  image text,
  status text default 'active',
  discount integer,
  expiry timestamptz,
  is_red_label boolean default false,
  created_at timestamptz default now()
);
create index if not exists deals_location_idx on public.deals (lat, lng);
create index if not exists deals_status_idx on public.deals (status);

-- ========== 2. FONKSİYONLAR (uuid::text kullan) ==========
create or replace function public.upsert_user_ticket(p_user_id text, p_draw_week integer, p_add integer default 1)
returns void language plpgsql security definer set search_path = public as $$
begin
  insert into public.user_tickets (user_id, draw_week, tickets, updated_at)
  values (p_user_id, p_draw_week, least(p_add, 42), now())
  on conflict (user_id, draw_week)
  do update set tickets = least(public.user_tickets.tickets + p_add, 42), updated_at = now();
end;
$$;

create or replace function public.grant_deal_tickets()
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  uid uuid;
  v_draw_week integer;
begin
  uid := auth.uid();
  if uid is null then
    raise exception 'User not authenticated';
  end if;
  v_draw_week := extract(week from (now() at time zone 'Asia/Jakarta'))::integer;
  perform public.upsert_user_ticket(uid::text, v_draw_week, 2);
  insert into public.lottery_tickets (user_id, draw_week)
  select uid::text, v_draw_week from generate_series(1, 2);
  return jsonb_build_object('success', true, 'tickets_added', 2);
end;
$$;

grant execute on function public.grant_deal_tickets() to authenticated;
grant execute on function public.grant_deal_tickets() to anon;

-- ========== 3. RLS - uuid/text karşılaştırmalarında HER ZAMAN ::text kullan ==========
-- user_stats: user_id text → (user_id::text) = (auth.uid()::text)
alter table public.user_stats enable row level security;
drop policy if exists "Users select own stats" on public.user_stats;
drop policy if exists "Users can read user_stats" on public.user_stats;
drop policy if exists "User stats select" on public.user_stats;
create policy "User stats select"
  on public.user_stats for select to anon, authenticated using (true);

-- user_tickets: user_id text → (user_id::text) = (auth.uid()::text)
alter table public.user_tickets enable row level security;
drop policy if exists "Users can read own user_tickets" on public.user_tickets;
drop policy if exists "User tickets select own" on public.user_tickets;
create policy "User tickets select"
  on public.user_tickets for select to authenticated
  using ((user_id::text) = (auth.uid()::text));

-- deals
alter table public.deals enable row level security;
drop policy if exists "Authenticated users can insert deals" on public.deals;
drop policy if exists "Authenticated and anonymous users can insert deals" on public.deals;
drop policy if exists "Public insert deals" on public.deals;
drop policy if exists "Anyone can read deals" on public.deals;
drop policy if exists "Deals insert anon authenticated" on public.deals;
drop policy if exists "Deals select all" on public.deals;
create policy "Deals insert"
  on public.deals for insert to anon, authenticated with check (true);
create policy "Deals select"
  on public.deals for select to anon, authenticated using (true);

-- lottery_tickets, weekly_lottery, weekly_winners
alter table public.lottery_tickets enable row level security;
drop policy if exists "Lottery tickets select" on public.lottery_tickets;
create policy "Lottery tickets select"
  on public.lottery_tickets for select to anon, authenticated using (true);

alter table public.weekly_lottery enable row level security;
drop policy if exists "Anyone can read lottery results" on public.weekly_lottery;
drop policy if exists "Weekly lottery select" on public.weekly_lottery;
create policy "Weekly lottery select"
  on public.weekly_lottery for select to anon, authenticated using (true);

alter table public.weekly_winners enable row level security;
drop policy if exists "Users can read weekly_winners" on public.weekly_winners;
drop policy if exists "Weekly winners select" on public.weekly_winners;
create policy "Weekly winners select"
  on public.weekly_winners for select to anon, authenticated using (true);

-- ========== 4. STORAGE BUCKETS ==========
insert into storage.buckets (id, name, public)
values ('receipts', 'receipts', true)
on conflict (id) do update set public = excluded.public;

insert into storage.buckets (id, name, public)
values ('promos', 'promos', true)
on conflict (id) do update set public = excluded.public;

insert into storage.buckets (id, name, public)
values ('deals', 'deals', true)
on conflict (id) do update set public = excluded.public;

-- ========== 5. STORAGE POLİTİKALARI - Tam erişim (anon + authenticated) ==========
drop policy if exists "Receipts bucket insert" on storage.objects;
drop policy if exists "Receipts bucket insert all" on storage.objects;
drop policy if exists "Receipts bucket select" on storage.objects;
drop policy if exists "Promos bucket insert" on storage.objects;
drop policy if exists "Promos bucket insert all" on storage.objects;
drop policy if exists "Promos bucket select" on storage.objects;
drop policy if exists "Deals bucket insert" on storage.objects;
drop policy if exists "Deals bucket insert all" on storage.objects;
drop policy if exists "Deals bucket select" on storage.objects;
drop policy if exists "Users can upload to deals folder" on storage.objects;
drop policy if exists "Public read deals images" on storage.objects;
drop policy if exists "receipts_insert" on storage.objects;
drop policy if exists "receipts_select" on storage.objects;
drop policy if exists "receipts_update" on storage.objects;
drop policy if exists "promos_insert" on storage.objects;
drop policy if exists "promos_select" on storage.objects;
drop policy if exists "promos_update" on storage.objects;
drop policy if exists "deals_insert" on storage.objects;
drop policy if exists "deals_select" on storage.objects;
drop policy if exists "deals_update" on storage.objects;

-- receipts: INSERT + SELECT
create policy "receipts_insert"
  on storage.objects for insert to anon, authenticated
  with check (bucket_id = 'receipts');
create policy "receipts_select"
  on storage.objects for select to anon, authenticated
  using (bucket_id = 'receipts');
create policy "receipts_update"
  on storage.objects for update to anon, authenticated
  using (bucket_id = 'receipts');

-- promos: INSERT + SELECT
create policy "promos_insert"
  on storage.objects for insert to anon, authenticated
  with check (bucket_id = 'promos');
create policy "promos_select"
  on storage.objects for select to anon, authenticated
  using (bucket_id = 'promos');
create policy "promos_update"
  on storage.objects for update to anon, authenticated
  using (bucket_id = 'promos');

-- deals: INSERT + SELECT
create policy "deals_insert"
  on storage.objects for insert to anon, authenticated
  with check (bucket_id = 'deals');
create policy "deals_select"
  on storage.objects for select to anon, authenticated
  using (bucket_id = 'deals');
create policy "deals_update"
  on storage.objects for update to anon, authenticated
  using (bucket_id = 'deals');
