-- Deals table for Red Label (Kırmızı Etiket) map pins
-- Run in Supabase SQL Editor if table does not exist

create table if not exists public.deals (
  id bigint generated by default as identity primary key,
  lat double precision not null,
  lng double precision not null,
  product_name text,
  price integer,
  store text,
  image text,
  status text default 'active',
  discount integer,
  expiry timestamptz,
  is_red_label boolean default false,
  created_at timestamptz default now()
);

create index if not exists deals_location_idx on public.deals (lat, lng);
create index if not exists deals_status_idx on public.deals (status);

alter table public.deals enable row level security;

create policy "Anyone can read deals"
  on public.deals for select
  using (true);

create policy "Authenticated users can insert deals"
  on public.deals for insert
  with check (auth.role() = 'authenticated');

-- Storage: Create bucket "deals" or use "promos" for deal images
-- Supabase Dashboard > Storage > New bucket "deals" (public)
