-- Community Promo Sharing System
-- Run in Supabase SQL Editor

-- 0. user_locations table (for 5km push notifications)
create table if not exists public.user_locations (
  user_id uuid primary key references auth.users(id) on delete cascade,
  latitude double precision not null,
  longitude double precision not null,
  updated_at timestamptz default now()
);

create index if not exists user_locations_coords_idx on public.user_locations (latitude, longitude);

alter table public.user_locations enable row level security;

create policy "Users can upsert own location"
  on public.user_locations for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- 1. promos table
create table if not exists public.promos (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  photo_url text not null,
  product_name text not null,
  discount integer not null check (discount >= 1 and discount <= 100),
  store_name text not null,
  latitude double precision not null,
  longitude double precision not null,
  created_at timestamptz default now(),
  status text not null default 'pending' check (status in ('pending', 'verified', 'expired'))
);

create index if not exists promos_user_id_idx on public.promos (user_id);
create index if not exists promos_created_at_idx on public.promos (created_at desc);
create index if not exists promos_status_idx on public.promos (status);
create index if not exists promos_location_idx on public.promos (latitude, longitude);

-- 2. promo_votes table
create table if not exists public.promo_votes (
  id bigint generated by default as identity primary key,
  promo_id bigint not null references public.promos(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  vote_type text not null check (vote_type in ('positive', 'negative')),
  created_at timestamptz default now(),
  unique(promo_id, user_id)
);

create index if not exists promo_votes_promo_id_idx on public.promo_votes (promo_id);
create index if not exists promo_votes_user_id_idx on public.promo_votes (user_id);

-- 3. Storage bucket for promo photos
-- Create in Supabase Dashboard > Storage > New bucket
-- Name: promos
-- Public: Yes (to allow reading promo images)

-- 4. RLS policies
alter table public.promos enable row level security;
alter table public.promo_votes enable row level security;

create policy "Anyone can read promos"
  on public.promos for select
  using (true);

create policy "Authenticated users can insert promos"
  on public.promos for insert
  with check (auth.uid() = user_id);

create policy "Users can update own promos"
  on public.promos for update
  using (auth.uid() = user_id);

create policy "Anyone can read promo_votes"
  on public.promo_votes for select
  using (true);

create policy "Authenticated users can insert promo_votes"
  on public.promo_votes for insert
  with check (auth.uid() = user_id);

-- 5. Function to update promo status based on votes
create or replace function public.update_promo_status_from_votes()
returns trigger
language plpgsql
security definer
as $$
declare
  v_positive int;
  v_negative int;
  v_promo_user_id uuid;
  v_verifier_user_id uuid;
begin
  select count(*) filter (where vote_type = 'positive'),
         count(*) filter (where vote_type = 'negative')
  into v_positive, v_negative
  from public.promo_votes
  where promo_id = coalesce(new.promo_id, old.promo_id);

  if v_positive >= 3 then
    update public.promos set status = 'verified' where id = coalesce(new.promo_id, old.promo_id);
    -- Grant +10 cuan to submitter, +2 cuan to each verifier (handled in app for flexibility)
  elsif v_negative >= 3 then
    update public.promos set status = 'expired' where id = coalesce(new.promo_id, old.promo_id);
  end if;

  return coalesce(new, old);
end;
$$;

drop trigger if exists promo_votes_status_trigger on public.promo_votes;
create trigger promo_votes_status_trigger
  after insert or delete on public.promo_votes
  for each row execute function public.update_promo_status_from_votes();

-- 6. Function to grant rewards when promo becomes verified
create or replace function public.grant_promo_rewards()
returns trigger
language plpgsql
security definer
as $$
declare
  v_user_id uuid;
  v_verifier_ids uuid[];
begin
  if new.status <> 'verified' or old.status = 'verified' then
    return new;
  end if;

  -- +10 cuan to submitter
  insert into public.user_stats (user_id, cuan)
  values (new.user_id, 10)
  on conflict (user_id) do update set
    cuan = public.user_stats.cuan + 10,
    updated_at = now();

  insert into public.notifications (user_id, title, message)
  values (new.user_id, 'Promo Terverifikasi!', 'Promo kamu dapat +10 cuan!');

  -- +2 cuan to each verifier (positive vote)
  select array_agg(distinct user_id) into v_verifier_ids
  from public.promo_votes
  where promo_id = new.id and vote_type = 'positive';

  if v_verifier_ids is not null then
    foreach v_user_id in array v_verifier_ids loop
      insert into public.user_stats (user_id, cuan)
      values (v_user_id, 2)
      on conflict (user_id) do update set
        cuan = public.user_stats.cuan + 2,
        updated_at = now();

      insert into public.notifications (user_id, title, message)
      values (v_user_id, 'Verifikasi Berhasil', 'Kamu dapat +2 cuan karena verifikasi promo!');
    end loop;
  end if;

  return new;
end;
$$;

drop trigger if exists promos_verified_rewards_trigger on public.promos;
create trigger promos_verified_rewards_trigger
  after update on public.promos
  for each row execute function public.grant_promo_rewards();

-- 7. Notify users within 5km when new promo is created
-- Uses simple bounding box (~0.045 deg ≈ 5km at equator)
create or replace function public.notify_nearby_users_on_promo()
returns trigger
language plpgsql
security definer
as $$
declare
  v_lat_delta float := 0.045;
  v_lng_delta float := 0.045 / cos(radians(new.latitude));
  v_row record;
  v_dist_km float;
  v_msg text;
begin
  v_msg := new.store_name || E'\nDiskon ' || new.discount || '%';
  for v_row in
    select ul.user_id, ul.latitude, ul.longitude
    from public.user_locations ul
    where ul.user_id <> new.user_id
      and ul.latitude between new.latitude - v_lat_delta and new.latitude + v_lat_delta
      and ul.longitude between new.longitude - v_lng_delta and new.longitude + v_lng_delta
  loop
    v_dist_km := 6371 * acos(
      cos(radians(new.latitude)) * cos(radians(v_row.latitude)) *
      cos(radians(v_row.longitude) - radians(new.longitude)) +
      sin(radians(new.latitude)) * sin(radians(v_row.latitude))
    );
    if v_dist_km <= 5 then
      insert into public.notifications (user_id, title, message)
      values (
        v_row.user_id,
        '🔥 Promo dekat kamu!',
        v_msg || E'\n\n' || round(v_dist_km::numeric, 1) || ' km dari kamu'
      );
    end if;
  end loop;
  return new;
end;
$$;

drop trigger if exists promos_notify_nearby_trigger on public.promos;
create trigger promos_notify_nearby_trigger
  after insert on public.promos
  for each row execute function public.notify_nearby_users_on_promo();
