-- Referral Invite System
-- Run in Supabase SQL Editor

-- 1. Add referral_code to profiles
alter table public.profiles
  add column if not exists referral_code text unique;

-- Generate referral codes for existing users (run once)
create or replace function public.ensure_referral_code()
returns trigger
language plpgsql
security definer
as $$
declare
  v_code text;
  v_exists boolean;
begin
  if new.referral_code is null or new.referral_code = '' then
    loop
      v_code := upper(substring(md5(random()::text || new.id::text) from 1 for 6));
      select exists(select 1 from public.profiles where referral_code = v_code and id <> new.id) into v_exists;
      exit when not v_exists;
    end loop;
    new.referral_code := v_code;
  end if;
  return new;
end;
$$;

drop trigger if exists profiles_ensure_referral_code on public.profiles;
create trigger profiles_ensure_referral_code
  before insert or update on public.profiles
  for each row execute function public.ensure_referral_code();

-- Backfill referral_code for existing profiles
update public.profiles set updated_at = now() where referral_code is null or referral_code = '';

-- 2. Create referrals table
create table if not exists public.referrals (
  id bigint generated by default as identity primary key,
  referrer_user_id uuid not null references auth.users(id) on delete cascade,
  referred_user_id uuid not null references auth.users(id) on delete cascade,
  reward_given boolean not null default false,
  created_at timestamptz default now(),
  unique(referred_user_id)
);

create index if not exists referrals_referrer_idx on public.referrals (referrer_user_id);
create index if not exists referrals_referred_idx on public.referrals (referred_user_id);

alter table public.referrals enable row level security;

create policy "Users can read own referrals"
  on public.referrals for select
  using (auth.uid() = referrer_user_id or auth.uid() = referred_user_id);

create policy "Users can insert referrals (for signup)"
  on public.referrals for insert
  with check (auth.uid() = referred_user_id);

-- 3. Trigger: when referred user uploads first receipt, grant rewards
create or replace function public.on_first_receipt_referral_reward()
returns trigger
language plpgsql
security definer
as $$
declare
  v_referral record;
  v_receipt_count int;
begin
  select count(*) into v_receipt_count
  from public.receipts
  where user_id = new.user_id;

  if v_receipt_count <> 1 then
    return new;
  end if;

  select * into v_referral
  from public.referrals
  where referred_user_id = new.user_id::uuid and reward_given = false
  limit 1 for update;

  if v_referral is null then
    return new;
  end if;

  update public.referrals set reward_given = true where id = v_referral.id;

  insert into public.user_stats (user_id, tiket)
  values (v_referral.referrer_user_id::text, 1)
  on conflict (user_id) do update set
    tiket = public.user_stats.tiket + 1,
    updated_at = now();

  insert into public.user_stats (user_id, tiket)
  values (new.user_id, 1)
  on conflict (user_id) do update set
    tiket = public.user_stats.tiket + 1,
    updated_at = now();

  insert into public.notifications (user_id, title, message)
  values (v_referral.referrer_user_id::text, 'Referral Reward!', 'Teman yang kamu undang sudah upload struk pertama. Kamu dapat +1 tiket!');

  insert into public.notifications (user_id, title, message)
  values (new.user_id, 'Referral Bonus!', 'Kamu dapat +1 tiket dari undangan teman!');

  return new;
end;
$$;

drop trigger if exists receipts_referral_reward_trigger on public.receipts;
create trigger receipts_referral_reward_trigger
  after insert on public.receipts
  for each row execute function public.on_first_receipt_referral_reward();
