-- Referral Invite System (user_stats tabanlı - profiles YOK)
-- Run in Supabase SQL Editor

-- 1. user_stats'a referral_code ekle
alter table public.user_stats
  add column if not exists referral_code text unique;

-- Mevcut kullanıcılar için referral_code üret (trigger ile otomatik)
create or replace function public.ensure_referral_code_user_stats()
returns trigger
language plpgsql
security definer
as $$
declare
  v_code text;
  v_exists boolean;
begin
  if new.referral_code is null or new.referral_code = '' then
    loop
      v_code := upper(substring(md5(random()::text || new.user_id::text) from 1 for 6));
      select exists(select 1 from public.user_stats where referral_code = v_code and user_id <> new.user_id) into v_exists;
      exit when not v_exists;
    end loop;
    new.referral_code := v_code;
  end if;
  return new;
end;
$$;

drop trigger if exists user_stats_ensure_referral_code on public.user_stats;
create trigger user_stats_ensure_referral_code
  before insert or update on public.user_stats
  for each row execute function public.ensure_referral_code_user_stats();

-- Mevcut user_stats satırları için referral_code doldur (trigger tetiklemek için güncelle)
update public.user_stats set updated_at = now() where referral_code is null or referral_code = '';

-- 2. referrals tablosu (referrer_user_id, referred_user_id = user_stats.user_id text)
create table if not exists public.referrals (
  id bigint generated by default as identity primary key,
  referrer_user_id text not null,
  referred_user_id text not null,
  reward_given boolean not null default false,
  created_at timestamptz default now(),
  unique(referred_user_id)
);

create index if not exists referrals_referrer_idx on public.referrals (referrer_user_id);
create index if not exists referrals_referred_idx on public.referrals (referred_user_id);

alter table public.referrals enable row level security;

drop policy if exists "Users can read own referrals" on public.referrals;
create policy "Users can read own referrals"
  on public.referrals for select
  using (auth.uid()::text = referrer_user_id or auth.uid()::text = referred_user_id);

drop policy if exists "Users can insert referrals (for signup)" on public.referrals;
create policy "Users can insert referrals (for signup)"
  on public.referrals for insert
  with check (auth.uid()::text = referred_user_id);
