-- =============================================================================
-- Rewards Marketplace: Ülkeye göre ödüller, dijital kodlar, Satın Al
-- Supabase SQL Editor'da çalıştırın.
-- =============================================================================

-- 1) REWARDS tablosu (ülkeye göre hediye çekleri)
create table if not exists public.rewards (
  id bigint generated by default as identity primary key,
  country_code char(2) not null check (country_code ~ '^[A-Z]{2}$'),
  name text not null,
  description text,
  provider text not null,
  cuan_cost integer not null check (cuan_cost > 0),
  voucher_amount integer not null default 0,
  image_url text,
  created_at timestamptz default now()
);

alter table public.rewards add column if not exists voucher_amount integer not null default 0;

create index if not exists rewards_country_code_idx on public.rewards (country_code);

-- 2) REWARD_CODES tablosu (hazır dijital kodlar)
create table if not exists public.reward_codes (
  id bigint generated by default as identity primary key,
  reward_id bigint not null references public.rewards(id) on delete cascade,
  code text not null,
  user_id text,
  claimed_at timestamptz,
  created_at timestamptz default now(),
  unique (reward_id, code)
);

create index if not exists reward_codes_reward_id_idx on public.reward_codes (reward_id);
create index if not exists reward_codes_available_idx on public.reward_codes (reward_id) where claimed_at is null;

-- 3) Örnek ödüller: ID (Alfamart), DE (Amazon.de, Lidl) - sadece tablo boşsa
insert into public.rewards (country_code, name, description, provider, cuan_cost, voucher_amount)
select 'ID', 'Alfamart 50.000', 'Hediye çeki 50.000 Rp', 'Alfamart', 500, 50000 where (select count(*) from public.rewards) = 0
union all select 'ID', 'Alfamart 100.000', 'Hediye çeki 100.000 Rp', 'Alfamart', 1000, 100000 where (select count(*) from public.rewards) = 0
union all select 'DE', 'Amazon.de 10€', 'Amazon.de Geschenkgutschein 10€', 'Amazon.de', 1000, 10 where (select count(*) from public.rewards) = 0
union all select 'DE', 'Amazon.de 25€', 'Amazon.de Geschenkgutschein 25€', 'Amazon.de', 2500, 25 where (select count(*) from public.rewards) = 0
union all select 'DE', 'Lidl 5€', 'Lidl Geschenkkarte 5€', 'Lidl', 500, 5 where (select count(*) from public.rewards) = 0
union all select 'DE', 'Lidl 10€', 'Lidl Geschenkkarte 10€', 'Lidl', 1000, 10 where (select count(*) from public.rewards) = 0;

-- 4) Örnek dijital kodlar (her reward için 5 kod - o reward'da kod yoksa)
insert into public.reward_codes (reward_id, code)
select r.id, 'CODE-' || r.id || '-' || s
from public.rewards r
cross join generate_series(1, 5) s
where (select count(*) from public.reward_codes rc where rc.reward_id = r.id) = 0;

-- 5) RPC: redeem_reward - cuan düş, kod tahsis et, döndür
create or replace function public.redeem_reward(p_reward_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  uid text;
  v_reward_country char(2);
  v_user_country char(2);
  v_cost integer;
  v_cuan integer;
  v_code_id bigint;
  v_code text;
begin
  uid := auth.uid()::text;
  if uid is null then
    raise exception 'User not authenticated';
  end if;

  select r.cuan_cost, r.country_code into v_cost, v_reward_country
  from public.rewards r where r.id = p_reward_id;
  if v_cost is null then
    raise exception 'Reward not found';
  end if;

  select us.cuan, us.country_code into v_cuan, v_user_country
  from public.user_stats us where us.user_id::text = uid limit 1;
  if v_cuan is null then
    raise exception 'User stats not found';
  end if;
  if v_cuan < v_cost then
    raise exception 'INSUFFICIENT_CUAN';
  end if;

  if coalesce(v_user_country, 'ID') <> v_reward_country then
    raise exception 'Reward not available for your country';
  end if;

  -- Kilitli bir satır seç (FOR UPDATE SKIP LOCKED)
  select rc.id, rc.code into v_code_id, v_code
  from public.reward_codes rc
  where rc.reward_id = p_reward_id and rc.claimed_at is null
  limit 1 for update skip locked;

  if v_code is null then
    raise exception 'NO_CODES_AVAILABLE';
  end if;

  -- Kodu tahsis et
  update public.reward_codes
  set user_id = uid, claimed_at = now()
  where id = v_code_id;

  -- Cuan düş
  update public.user_stats
  set cuan = cuan - v_cost, updated_at = now()
  where user_id::text = uid;

  return jsonb_build_object('success', true, 'code', v_code, 'reward_id', p_reward_id);
end;
$$;

grant execute on function public.redeem_reward(bigint) to authenticated;

-- 6) RLS
alter table public.rewards enable row level security;
alter table public.reward_codes enable row level security;

drop policy if exists "Rewards select by country" on public.rewards;
create policy "Rewards select by country"
  on public.rewards for select to authenticated using (true);

drop policy if exists "Reward codes insert admin" on public.reward_codes;
create policy "Reward codes select own"
  on public.reward_codes for select to authenticated
  using (user_id = auth.uid()::text);
