import { Link } from "react-router-dom";
import { ArrowLeft } from "lucide-react";

export default function CommunityGuidelines() {
  return (
    <div className="min-h-screen max-w-[420px] mx-auto px-4 py-6 pb-12">
      <Link
        to="/home"
        className="inline-flex items-center gap-2 text-muted-foreground hover:text-primary mb-6 transition-colors"
      >
        <ArrowLeft size={18} />
        <span className="text-sm">Back</span>
      </Link>

      <h1 className="font-display text-2xl font-bold text-foreground mb-4">
        Community Guidelines
      </h1>

      <div className="prose prose-invert prose-sm max-w-none text-muted-foreground space-y-5">
        <p className="text-sm leading-relaxed font-semibold text-white/80">
          StrukCuan relies on trust and authentic engagement. To keep the reward ecosystem fair for all active draw participants, you must adhere to these policies.
        </p>

        <section>
          <h2 className="text-base font-bold text-white mb-2">1. Valid Usage & Uploads</h2>
          <ul className="list-disc pl-5 space-y-1">
            <li><strong>Be Honest:</strong> Only upload valid physical supermarket receipts originally generated by your own purchases.</li>
            <li><strong>Do Not Share:</strong> Passing physical receipts to friends or sharing photos across social groups to "farm" identical receipts constitutes fraudulent conspiracy. Admins and AI will reject them.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-base font-bold text-white mb-2">2. Respect the Ecosystem</h2>
          <ul className="list-disc pl-5 space-y-1">
            <li><strong>No Bots or Emulators:</strong> Using automated scripts, VPNs to mask identity, rooted software trickery, or parallel account clones (e.g. Dual Space) is permanently bannable.</li>
            <li><strong>Respect Moderation:</strong> Moderation decisions (approval/rejections) are final. If AI flags your receipt as manipulated or blurry, please capture a clearer image of a valid original receipt next time. Do not repeatedly upload a known rejected receipt—doing so risks your account.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-base font-bold text-white mb-2">3. Zero Harassment</h2>
          <p className="text-sm leading-relaxed text-red-200/90 mb-2">
            Harassing StrukCuan administrators, support channels, or partner companies regarding denied tickets, reward values, or technical delays is prohibited and will result in strict account termination.
          </p>
        </section>

      </div>
    </div>
  );
}
